### ISSUE TITLE
How do i configure this for my existing sanity studio?

### ISSUE THREAD

**Issue by vowval** [easyblockshq/easyblocks#29]
Our Sanity Studio is hosted with vercel. Please give me configuration details and how do i use the existing schema data.

**Comment by r00dY** [comment]
Hey, this repo is about Easyblocks, not Shopstory. Shopstory project is discontinued. Easyblocks is a framework which is lower level abstraction, it doesn't handle specific host systems like headless CMSes or ecommerce platforms.

However, you can absolutely integrate Easyblocks with Sanity Studio, please refer to the docs (https://docs.easyblocks.io/) and check out our page builder example: https://github.com/easyblockshq/page-builder-demo

**Comment by vowval** [comment]
Thank you!
