### ISSUE TITLE
"Missing" error message from External data card

### ISSUE THREAD

**Issue by tring-harshini** [easyblockshq/easyblocks#38]
I have tried to add a new card template which renders data from external API and got a missing message while selecting the card.

- I have created No-code component for my External data Card.
- I have created a type ExternalCard in easyblocksConfig 
`externalCard: {
      type: "external",
      widgets: [externalCardWidget],
    },`

`export const externalCardWidget: Widget = {
  id: "3",
  label: "externalCard",
};`

- And then created a widget component using select

`export function ExternalCardPickerWidget(props: WidgetComponentProps<string>) {
  return (
    <select
      value={props.id ?? ""}
      onChange={(event) => {
        props.onChange(event.target.value === "" ? null : event.target.value);
      }}
    >
      <option value={""}>Select a article</option>
      {products.map((p) => (
        <option value={p.id} key={p.id}>
          {p.title}
        </option>
      ))}
    </select>
  );
}`

- Added the new external data component to EasyblocksEditor components

![externalCard](https://github.com/easyblockshq/easyblocks/assets/91422976/966312c6-108c-40b5-9f14-48300c4399e2)

![externalCard_missing](https://github.com/easyblockshq/easyblocks/assets/91422976/31977432-dcc1-49eb-964c-1e07fd593255)

**Comment by r00dY** [comment]
@tring-harshini have you provided component the reference to your component instance to the `components` property of `EasyblocksEditor`?

**Comment by tring-harshini** [comment]
> @tring-harshini have you provided component the reference to your component instance to the `components` property of `EasyblocksEditor`?

Yes I have added it

![image](https://github.com/easyblockshq/easyblocks/assets/91422976/25472a7e-7e06-4b7c-9bc8-b6ff269b1738)

`<EasyblocksEditor
      config={easyblocksConfig}
      externalData={externalData}
      onExternalDataChange={async (externals) => {
        const fetchedExternalData = await myCustomFetch(externals);
        const removedExternals = Object.entries(externals)
          .filter(
            ([id, externalDataValue]) =>
              externalDataValue.id === null && externalData[id]
          )
          .map(([externalId]) => externalId);

        const newExternalData: ExternalData = {
          ...externalData,
          ...fetchedExternalData,
        };

        for (const removedExternalId of removedExternals) {
          delete newExternalData[removedExternalId];
        }

        setExternalData(newExternalData);
      }}
      components={components}
      widgets={{
        [mockImageWidget.id]: MockImagePicker,
        [mockVideoWidget.id]: MockVideoPicker,
        [productWidget.id]: ProductPicker,
        [pexelsImageWidget.id]: PexelsImagePicker,
        [pexelsVideoWidget.id]: PexelsVideoPicker,
        [articleWidget.id]: ArticlePickerWidget,
        [externalCardWidget.id]: ExternalCardPickerWidget,
        url: UrlWidget,
      }}
      __debug={true}
    />`

**Comment by tring-harshini** [comment]
ExternalCard.tsx 

const ExternalCard = (product: any) => {
  return (
    <div>
      <h1>{product?.title}</h1>
      <p>{product?.price}</p>
    </div>
  );
};

export { ExternalCard };

**Comment by r00dY** [comment]
@tring-harshini This is a component. I'm asking for component definition from config file (`easyblocks.config.ts`)

**Comment by tring-harshini** [comment]
export const easyblocksConfig: Config = {
  backend: new EasyblocksBackend({
    accessToken: process.env.NEXT_PUBLIC_EASYBLOCKS_ACCESS_TOKEN,
  }),
  locales: [
    {
      code: "en-US",
      isDefault: true,
    },
    {
      code: "de-DE",
      fallback: "en-US",
    },
  ],
  components: [
    ExternalCardDefinition,
  ],
  types: {
    "@easyblocks/image": {
      type: "external",
      widgets: [mockImageWidget, pexelsImageWidget],
    },
    "@easyblocks/video": {
      type: "external",
      widgets: [mockVideoWidget],
    },
    externalCard: {
      type: "external",
      widgets: [externalCardWidget],
    },

**Comment by r00dY** [comment]
In `components` property you use the component name starting with a capital letter: `ExternalCard`. In the component definition (https://github.com/vowval/easyblocks/blob/67ee6c56f06ac577623fc201d2aa206b79ae6559/src/app/easyblocks/components/ExternalCard/ExternalCard.definition.ts#L4) you use use `externalCard` as an `id`. The ids are not equal so Easyblocks can't match them. 

The key for component instance in `components` property must be identical to component `id` from the definition.
