### ISSUE TITLE
Defect: Complete crypto-js included into the bundle along with @easyblocks/core

### ISSUE THREAD

**Issue by chudesno** [easyblockshq/easyblocks#67]
### Description
Complete crypto-js included into the bundle along with @easyblocks/core

Commit 7b9836b304e885c1d4251deabc03105c9dad4035 forces a whole crypto-js lib to be included with @easyblocks/core. 
We bundle with rollup and it cannot tree-shake redundant code out of it. That adds quite a lot to the final bundle - 59KB GZip'ed.

------------------------------------------------------
In general crypto-js project is discontinued. Would it be possible to rely on browser crypto API instead?

**Comment by chudesno** [comment]
Okay, native crypto is async and may be not feasible in otherwise sync context. I would try using md5 instead.

**Comment by r00dY** [comment]
Hi @chudesno, you're right, it should be an easy fix. Should find some time today / tomorrow to push it.

**Comment by r00dY** [comment]
@chudesno actually I think that it should be tree-shakable, curious why it doesn't work. But also don't think it's worth debugging too much, I'll soon merge a PR with quite a big refactor (https://github.com/easyblockshq/easyblocks/pull/66) so I'll look into it in the process. 

In the meantime, changed `crypto-js` to `js-xxhash`: https://github.com/easyblockshq/easyblocks/pull/69, it's 1.5KB, should be good for now.

Released in `1.0.10`

**Comment by chudesno** [comment]
Looks awesome! Many thanks!
